#Problem 2
#Each new term in the Fibonacci sequence is
#generated by adding the previous two terms.
#By starting with 1 and 2, the first 10 terms will
#be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ..
#By considering the terms in the Fibonacci sequence
#whose values do not exceed four million, find the
#sum of the even-valued terms.

end = 4000000
fib1 = 1
fib2 = 2
fib3 = fib1 + fib2
summ = 2

while (fib3 < end):
	fib1 = fib2
	fib2 = fib3
	fib3 = fib1 + fib2
	if (fib3%2==0):
		summ = summ + fib3
print(summ)